### ISSUE TITLE
Zenfolio API Error for method LoadPhotoSetPhotos

### ISSUE THREAD

**Issue by NagarajanCerulean** [lildude/phpZenfolio#20] opened 2016-12-28 13:20 UTC
Hi,

There are 3 groups(albums) in my Zenfolio account called Homepage, Portfolio and Client Galleries.
Here 'Client Galleries' group having 2 more groups called 2015 and 2016 but both are **Empty**.

API :             phpZenfolio.php 1.3
->**LoadGroupHierarchy($username)**;
Its loaded all the groups available(Homepage, Portfolio and Client Galleries) from Zenfolio account after Successful Authentication. 
->**LoadPhotoSetPhotos($albumId, 0, $imagesCount)**;     here $imageCount = 0; (No images for that group)
When i try to call this method for 'Client Galeries>>2015 OR Client Galeries>>2016' groups, its returning the following error.
             **Zenfolio API Error for method LoadPhotoSetPhotos: E_NOSUCHOBJECT**
But its working fine and returning the right images for Other groups  "Homepage, Portfolio" which are having images.
So, I request you to provide the solution for this issue.

Thank you,
Nagarajan

**Comment by lildude** [comment] 2016-12-28 13:38
@NagarajanCerulean the problem you are getting here sounds like a common permissions problem commonly seen when using a partner account to access private galleries and photos owned by another user as discussed in https://github.com/lildude/phpZenfolio/issues/16#issuecomment-237539007

Do you own the galleries you are having problems accessing or are they owned by another user account?  If the latter, you will need to ensure they grant you the permissions you need.

**Comment by lildude** [comment] 2017-01-13 17:20
@NagarajanCerulean did you get to the bottom of your issue?

**Comment by lildude** [comment] 2017-03-01 09:40
I'm going to take the 📻  🤐  as confirmation that your issue was a permissions issue caused by using a partner account @NagarajanCerulean so I'm going to close this issue.  Feel free to re-open if this isn't the case and you need further assistance.

**Closed by lildude** 2017-03-01 09:40 UTC
