### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by verygoodplugins** [lildude/phpZenfolio#11] opened 2016-02-16 19:22 UTC
Is this project still supported? I see there haven't been any updates in several years and I keep getting E_DEPRECATEDVERSION messages when I issue some commands, like CreatePhotoSet, upload, CreateGroup, etc.

**Comment by lildude** [comment] 2016-04-14 17:20
Sorry about the delay in getting back to you; I accidentially stopped watching my own repo :blush:

Yes phpZenfolio is still maintained.

The warnings you are getting are caused by phpZenfolio stil defaulting to the 1.6 API which has now been deprecated.

You can resolve this by explicitly passing `APIVer=1.8` when instantiating the object.

I've also been informed that you may also need to add `|| $this->APIVer == '1.8' ` to line 549, though I've not tested of validated this yet.

Once again, sorry for the delay in getting back to you.

**Comment by verygoodplugins** [comment] 2016-04-14 17:23
Hey, Colin, thanks for getting back to me. I figured out the same through a
bit of trial and error. Would be good to add a note to the readme.

Cheers
Jack

**Comment by lildude** [comment] 2016-04-14 17:26
Good to hear it. I've been meaning to update phpZenfolio. It's been working perfectly as is for so long I've had little need to change anything :smile:.  This API version this is becoming quite common so I'll look to release an update soon.

As you've got this sorted now, I'll go ahead and close this issue.

**Closed by lildude** 2016-04-14 17:26 UTC

**Comment by lildude** [comment] 2016-04-14 17:37
Ah, looking back over my twitter feed, I think...

> I've also been informed that you may also need to add `|| $this->APIVer == '1.8'` to line 549, though I've not tested of validated this yet.

... came from you 😀

**Comment by verygoodplugins** [comment] 2016-04-14 17:57
Yerp :)

J
